version: 2.1
orbs:
  docker: circleci/docker@1.3.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2
        environment:
          PGHOST: localhost
          RACK_ENV: test
          RAILS_ENV: test
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_DB: circleci_sample_development
          POSTGRES_USER: circleci
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: create build version
          command: chmod +x build-version.sh && ./build-version.sh
      - run:
          # https://stackoverflow.com/questions/27472234/an-error-occurred-while-installing-rugged
          name: Install Cmake
          command: sudo apt-get install cmake
      - restore_cache:
          keys:
            - circleci_sample-bundle-{{ checksum "Gemfile.lock" }}
            - circleci_sample-bundle-
      - run:
          name: Bundle Check or Install
          command: bundle check --path vendor/bundle || bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: circleci_sample-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Create and Load Database
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Execute Rspec Tests
          command: |
            mkdir -p /tmp/coverage
            bundle exec rspec
      - run:
          name: Store coverage report
          command: |
            mv coverage/coverage.json /tmp/coverage/
            mv coverage/badge.svg /tmp/coverage/
      - persist_to_workspace:
          root: /tmp/coverage
          paths: .
      - store_artifacts:
          path: /tmp/coverage
          destination: coverage
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          treat-warnings-as-errors: true
